### ISSUE TITLE
Demo seems to be broken (CDN link to smitty.min.js is 404-ing)

### ISSUE THREAD

**Issue by nilliams** [tkh44/react-smitty#1]
404 in [demo](http://codepen.io/tkh44/pen/qRjjwb) linked to from the Readme for https://npmcdn.com/smitty@2.0.3/dist/smitty.min.js

> Not found: file "/dist/smitty.min.js" in package smitty@2.0.3

**Comment by tkh44** [comment]
Thank you for pointing this out. I changed the build and broke all the demos 😅

**Comment by tkh44** [comment]
Fixed
