### ISSUE TITLE
Using connect with mapStateToProps not passing props until a reducer is called

### ISSUE THREAD

**Issue by danhayden** [tkh44/react-smitty#2]
I have created a minimal [runnable example](https://www.webpackbin.com/bins/-KikLPzkceKIrwLRRRlK) on webpackbin to demonstate the issue

As you will see the state is not passed from mapStateToProps until a reducer is called by clicking on one of the buttons.

Do you have any idea what the issue might be or if I have set something up incorrectly.

Thanks

---

Dependencies:
react 15.5.4
react-dom 15.5.4
react-router-dom 4.1.1
react-smitty 2.0.6
smitty 2.0.3

**Comment by tkh44** [comment]
Def a bug. I've got a fix in place should be released soon.

**Comment by danhayden** [comment]
Thanks for the fast response!
Loving smitty and react-smitty by the way, great work :)

**Comment by tkh44** [comment]
@danhayden fixed and published in `v2.0.7` if you want to try it out.

**Comment by danhayden** [comment]
Hey just tried out `v2.0.7` and the state does now appear on load, however there appears to be a new issue now when calling a reducer. I have created a new [example](https://www.webpackbin.com/bins/-KikzydA5KBf0VWFA4EJ)

If you view the console on webpackbin it displays `Uncaught TypeError: Cannot read property 'forEach' of undefined` and the state is not updated

**Comment by danhayden** [comment]
I have opened a new issue for the problem https://github.com/tkh44/react-smitty/issues/3
