### ISSUE TITLE
`v2.0.7` errors when calling reducer

### ISSUE THREAD

**Issue by danhayden** [tkh44/react-smitty#3]
I have created a minimal [runnable example](https://www.webpackbin.com/bins/-KikzydA5KBf0VWFA4EJ) on webpackbin to demonstate the issue

If you view the console on webpackbin it displays when calling a reducer by clicking one on the buttons it displays `Uncaught TypeError: Cannot read property 'forEach' of undefined` and the state is not updated

---
Dependencies:
react 15.5.4
react-dom 15.5.4
react-router-dom 4.1.1
react-smitty 2.0.7
smitty 2.0.3

**Comment by tkh44** [comment]
Fixed in v2.0.8

**Comment by danhayden** [comment]
Thanks! I can confirm this is now working as expected, plus between the two latest versions react warnings that I had been receiving have also been resolved.
Great work! 😄
